baseURL: https://Saksham1611.github.io/resume
title: saksham.gupta
paginate: 5
theme: charlolamode
# canonifyURLs : true
publishDir: docs

menu:
    main:
        - name: Contact
          url: contact/
          weight: 25
        - name: Articles
          url: articles/
          weight: 20
        - name: Projects
          url: projects
          weight: 15

    #  - name: Categories
    #       url: categories/
    #       weight: 10
    #     - name: new Tab
    #       url: mewtab/
    #       weight: defines order of tabs
   


params:
    author: Author's Name


    defaultTheme: auto
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        enabled: true
        title: Hey there , I'm Saksham 👋  
        description: |
 
          I work as a `Data Scientist 👩‍💻` in an Analytics Firm
        

          Quick one liner for understanding the description . 
          Project links too for easy access .

        imageUrl: /images/profile.png
        imageTitle: You dont see me 
        imageWidth: 220
        imageHeight: 220

        buttons:
            - name: Don't click me
              url: https://www.youtube.com/watch?v=dQw4w9WgXcQ

    mainSections:
      - articles

    socialIcons:
        - name: twitter
          url:  https://twitter.com/capablegupta
        - name: github
          url:  https://github.com/Saksham1611
        - name: linkedin
          url:  https://www.linkedin.com/in/sakshamgupta1611/

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

